---
- name: Deploying Application to Elastic Kubernetes Service
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: final
  tasks:
    - name: Deploying Cilist chart using set values on target
      kubernetes.core.helm:
        name: chill
        chart_ref: cilist/chill
        release_namespace: "{{ namespace_name }}"
        values:
          data:
            url: "http://a04798ecfa5b0453ea6485848dde08a1-853923329.ap-southeast-2.elb.amazonaws.com:5000"

    - name: Deploying Traefik
      kubernetes.core.helm:
        name: trepik
        chart_ref: traefik/traefik
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer

    - name: Deploying Grafana chart using set values on target
      kubernetes.core.helm:
        name: graf
        chart_ref: grafana/grafana
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer

    - name: Deploying Prometheus chart using set values on target
      kubernetes.core.helm:
        name: prome
        chart_ref: prometheus/prometheus
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer
            
            
