---
- name: Deploying Application to Elastic Kubernetes Service
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: final
  tasks:
    - name: Creating Namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_file }}"
        name: "{{ namespace_name }}"
        api_version: v1
        kind: Namespace
        state: present

    - name: Deploying Cilist chart using set values on target
      kubernetes.core.helm:
        name: chill
        chart_ref: cilist/chill
        release_namespace: "{{ namespace_name }}"
        values:
          data:
            url: "http://a7a66caefeef04f699642c93bd12d616-273142279.ap-southeast-2.elb.amazonaws.com:5000"

    - name: Deploying Traefik
      kubernetes.core.helm:
        name: trepik
        chart_ref: traefik/traefik
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer

    - name: Deploying Prometheus chart using set values on target
      kubernetes.core.helm:
        name: prome
        chart_ref: prometheus/prometheus
        release_namespace: "{{ namespace_name }}"

    - name: Deploying Grafana chart using set values on target
      kubernetes.core.helm:
        name: graf
        chart_ref: grafana/grafana
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer
            
    - name: Deploying Datadog chart using set values on target
      kubernetes.core.helm:
        name: datadog
        chart_ref: datadog/datadog
        release_namespace: "{{ namespace_name }}"
        values:
          datadog:
            site: us5.datadoghq.com
            apiKey: YOUR_API_KEY
          logs:
            enabled: true
            containerCollectAll: true
            
