---
- name: Deploying Elastic Search Helm Deployment
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: final
  tasks:
    - name: Deploying Elastic Chart using set values on target
      kubernetes.core.helm:
        name: elasty
        chart_ref: elastic/elasticsearch
        release_namespace: "{{ namespace_name }}"
        chart_version: 8.5.1 
        values:
          replica: 1
          resources:
            limits:
              cpu: 3000m
              memory: 4Gi
          readinessProbe:
            initialDelaySeconds: 300

