---
- name: Deploying Application to Elastic Kubernetes Service
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: bry
  tasks:
    - name: Deploying Cilist chart using set values on target
      kubernetes.core.helm:
        name: chill
        chart_ref: cilist/chill
        release_namespace: "{{ namespace_name }}"
        values:
          data:
            url: "http://a5a694b3454654cbc9acccb4a3610614-124387888.ap-southeast-2.elb.amazonaws.com:5000"

    - name: Deploying Traefik
      kubernetes.core.helm:
        name: traefik
        chart_ref: traefik/traefik
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer

    - name: Deploying Grafana chart using set values on target
      kubernetes.core.helm:
        name: grif
        chart_ref: grafana/grafana
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer

    - name: Deploying Prometheus chart using set values on target
      kubernetes.core.helm:
        name: prim
        chart_ref: prometheus/prometheus
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer
            
            
