---
- name: Monitoring with EFK Stacks
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: final
  tasks:        
    - name: Deploying Filebeat Chart
      kubernetes.core.helm:
        name: fib
        chart_ref: elastic/filebeat
        release_namespace: "{{ namespace_name }}"
  
    - name: Deploying Metricbeat chart
      kubernetes.core.helm:
        name: mib
        chart_ref: elastic/metricbeat
        release_namespace: "{{ namespace_name }}"

    - name: Deploying Kibana Chart using set values on target
      kubernetes.core.helm:
        name: kibs
        chart_ref: elastic/kibana
        release_namespace: "{{ namespace_name }}"
        values:
          service:
            type: LoadBalancer
