---
- name: Removing Service Object from Elastic Kubernetes Service
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: final
  tasks:
    - name: Removing First Service object
      kubernetes.core.k8s:
        api_version: v1
        kind: Service
        namespace: "{{ namespace_name }}"
        name: first
        state: absent