---
- name: Removing Application from Elastic Kubernetes Service
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: bry
  tasks:
    - name: Removing First Service object
      kubernetes.core.k8s:
        api_version: v1
        kind: Service
        namespace: "{{ namespace_name }}"
        name: first
        state: absent

    - name: Removing Cilist Helm Deployment
      kubernetes.core.helm:
        name: chill
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true  

    - name: Removing Traefik Helm Deployment
      kubernetes.core.helm:
        name: traefik
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true  
        
    - name: Removing Prometheus Helm Deployment
      kubernetes.core.helm:
        name: prim
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true  

    - name: Removing Grafana Helm Deployment
      kubernetes.core.helm:
        name: grif
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true     


