---
- name: Removing Application from Elastic Kubernetes Service
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig_file: ~/.kube/config
    namespace_name: final
  tasks:
    - name: Removing Metricbeat Helm Deployment
      kubernetes.core.helm:
        name: mib
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true  

    - name: Removing Filebeat Helm Deployment
      kubernetes.core.helm:
        name: fib
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true      

    - name: Removing Kibana Helm Deployment
      kubernetes.core.helm:
        name: kibs
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true  

    - name: Removing Elastic Helm Deployment
      kubernetes.core.helm:
        name: elasty
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true  

    - name: Removing Datadog Helm Deployment
      kubernetes.core.helm:
        name: datadog
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true   

    - name: Removing Grafana Helm Deployment
      kubernetes.core.helm:
        name: graf
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true   

    - name: Removing Prometheus Helm Deployment
      kubernetes.core.helm:
        name: prome
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true  

    - name: Removing Traefik Helm Deployment
      kubernetes.core.helm:
        name: trepik
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true 

    - name: Removing Cilist Helm Deployment
      kubernetes.core.helm:
        name: chill
        release_namespace: "{{ namespace_name }}"
        state: absent
        wait: true 
    
    - name: Removing First Service object
      kubernetes.core.k8s:
        api_version: v1
        kind: Service
        namespace: "{{ namespace_name }}"
        name: first
        state: absent
